- name: "Install misc files"
  copy:
    src: "{{ dotfiles }}/{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: 0644
  with_items:
    - colordiffrc
    - emacs
    - ircrc
    - perldb
    - perltidyrc
    - pgclirc
    - pryrc
    - psqlrc
    - screenrc
    - tcshrc
    - terminfo
    - tmux.conf
